### ISSUE TITLE
The primary branch on rbenv/rbenv-installer repo has been changed to 'main' from 'master'

### ISSUE THREAD

**Issue by bschantz** [zzet/rbenv#147]
The `master` branch on https://github.com/rbenv/rbenv-installer has been renamed to `main`, causing the playbook to fail in the 'install plugins for selected users' task in [`tasks/user_install.yml`](https://github.com/zzet/rbenv/blob/be36c211a6ccaf31f228bdaaac6e658127c4fa6a/tasks/user_install.yml#L30)

I was able to workaround it by providing the value of `rbenv_plugins` as in [`defaults/main.yml`](https://github.com/zzet/rbenv/blob/be36c211a6ccaf31f228bdaaac6e658127c4fa6a/defaults/main.yml) with the updated branch name: 

```yaml
 - name: install ruby via rbenv
      include_role:
        name: zzet.rbenv
      vars:
        # ...
        rbenv_plugins:
          - { name: "rbenv-vars",         repo: "https://github.com/rbenv/rbenv-vars.git",         version: "master" }
          - { name: "ruby-build",         repo: "https://github.com/rbenv/ruby-build.git",         version: "master" }
          - { name: "rbenv-default-gems", repo: "https://github.com/rbenv/rbenv-default-gems.git", version: "master" }
          - { name: "rbenv-installer",    repo: "https://github.com/rbenv/rbenv-installer.git",    version: "main"   }
          - { name: "rbenv-update",       repo: "https://github.com/rkh/rbenv-update.git",         version: "master" }
          - { name: "rbenv-whatis",       repo: "https://github.com/rkh/rbenv-whatis.git",         version: "master" }
          - { name: "rbenv-use",          repo: "https://github.com/rkh/rbenv-use.git",            version: "master" }
```
