### ISSUE TITLE
The error was: 'dict object' has no attribute 'drop_ruby'

### ISSUE THREAD

**Issue by neidiom** [zzet/rbenv#150]
I am getting this error. Any ideas why?
````
FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'drop_ruby'\n\nThe error appears to be in '/home/nedim/.ansible/roles/zzet.rbenv/tasks/system_install.yml': line 97, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: remove old rubies\n  ^ here\n"}
````

**Comment by nathan-rollins** [comment]
When you override the rbenv variable object in the following manner, you are replacing the entire rbenv object. So you must include all the object variables, even those that you don't want to change:

```
rbenv:
  env: user  # changed from default
  version: v1.0.0
  default_ruby: 2.4.2
  rubies:
    - version: 2.4.2
```

Alternatively, override just the desired setting:

```
rbenv.env: user
```
